<?php

function cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Cipher',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
  );

    $items['cipher_results'] = array(
        'title' => 'Cipher',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
        'page callback' => 'cipher_results',
  );
    return $items;
}

function cipher_form() {
    $form['phrase'] = array(
        '#title' => 'Initial Phrase',
        '#type' => 'textfield',
        '#description' => 'Enter your initial phrase.',
        '#required' => TRUE,
        '#element_validate' => array('element_validate_phrase'),
    );

    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => 'Enter the direction to which you desire to shift the letters (left or right).',
        '#required' => TRUE,
        '#element_validate' => array('element_validate_direction'),
    );

    $form['shift_value']=array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => 'Enter number of spaces to shift the letters.',
        '#required' => TRUE,
        '#element_validate' => array('element_validate_cipher_value'),
  );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );

    return $form;
}

function element_validate_direction($element) {
     if(!strtolower($element['#value']) == 'left' || !strtolower($element['#value']) == 'right') {
        form_error($element, t('You must enter either "left" or "right"'));
    }
}

function element_validate_phrase($element) {
    $letters = str_split($element['#value']);
    $special_char = array("'", ' ', '!', '?', '.', ',');
    foreach ($letters as $letter) {
        if (!ctype_alpha($letter)) {
            if(!in_array($letter, $special_char)) {
                form_error($element, t("you may only encrypt letters in the alphabet, other charactes you can use include: ' ! . , ? or blank spaces in your phrase."));
            }
        }
    }
}
 function element_validate_cipher_value($element) {
    $value = $element["#value"];
    if (intval($value) < 1) {
      form_error($element, t('please enter a number greater than or equal to 1'));
    }
 }
